### ISSUE TITLE
Call to a member function getPageTemplateID() on a non-object

### ISSUE THREAD

**Issue by maschenborn** [cryophallion/C5Tutorial-ProgrammaticPageTypes#1]
If I try to install the controller, I get an error:
"Call to a member function getPageTemplateID() on a non-object"

**Comment by cryophallion** [comment]
I just tried installing it on a clean install, and it went fine. However... it was a clean install with the sample content, so maybe that has something to do with it?
Can you go to your dashboard->Pages&Themes->Page Templates and tell me if you have the full and left_sidebar templates installed? If you don't, what templates do you have installed?

**Comment by maschenborn** [comment]
thank you. I've installed the clean install without demo-data.
After creating the left_sidebar-Template, it worked.
