### ISSUE TITLE
addPage 

### ISSUE THREAD

**Issue by maschenborn** [cryophallion/C5Tutorial-ProgrammaticPageTypes#3]
The addPage method doesn't work for me.
Even in a fresh C5 installation with demo-content if I install the Package no Pages are created in the sitemap.

**Comment by cryophallion** [comment]
Are you getting any errors in your php logs on your system? I use the add page in this, and it worked for me.

**Comment by cryophallion** [comment]
It looks like you found the same bug in both packages. I'm fixing it now.
